import java.util.Arrays;

public class PasswordTest {
    public static void main(String[] args) {
	/* client code: */

	byte[] clientSalt = Password.genSalt(1024); // only know by the client
	Password client = new Password("My Password is secret!11elf",
				       clientSalt);
	client.genSaltedHash();
	
	/* server code: */

	Password server = new Password(client.getPassword());
	byte[] randomSalt = Password.genSalt(1024); // generated by the server

	client.genSaltedHash(randomSalt); // client code, randomSalt sent
	
	server.genSaltedHash(randomSalt); // server code, needed for validation
	
	// validate, done by the server
	if(Arrays.equals(client.getPassword(), server.getPassword()))
	    System.out.println("Client authorized.");
	else
	    System.out.println("This should not happen...");
    }
}
